/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package odevveri;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import odevveri.SıralamaAlgoritmalarıForSteps;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;



/**
 *
 * @author Sameet Acar
 */
public class interfaces extends javax.swing.JFrame {
static int[] dizi1;
 interfaces() {
       initComponents();
        
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DiziBoyutu = new javax.swing.JTextField();
        Algoritmalar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Cizdir = new javax.swing.JButton();
        sıralDizi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("        Dizi Boyutu :");

        DiziBoyutu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiziBoyutuActionPerformed(evt);
            }
        });

        Algoritmalar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lütfen Seciniz", "Selection Sort", "Insertion Sort", "Bubble Sort" }));
        Algoritmalar.setToolTipText("");
        Algoritmalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgoritmalarActionPerformed(evt);
            }
        });

        jLabel2.setText("       Sıralama Algoritmaları");

        Cizdir.setText("Cizdir");
        Cizdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CizdirActionPerformed(evt);
            }
        });

        jLabel4.setText("Sıralanmış Dizi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiziBoyutu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4))
                                    .addComponent(Algoritmalar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sıralDizi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(Cizdir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiziBoyutu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Algoritmalar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sıralDizi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cizdir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int[] diziOlustur() {
int diziBoyutu= Integer.parseInt(DiziBoyutu.getText());

int[] dizi1 = new int[diziBoyutu];
Random r = new Random();
for (int i = 0; i < diziBoyutu; i++) {
dizi1[i] = r.nextInt(1000);
}
return dizi1;
}
    private void AlgoritmalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgoritmalarActionPerformed
   dizi1=diziOlustur();
        switch (Algoritmalar.getSelectedItem().toString()) {
    case "Selection Sort" :sıralDizi.setText(Arrays.toString(SıralamaAlgoritmaları.selectionSort(dizi1))); break;
    case "Insertion Sort" : sıralDizi.setText(Arrays.toString(SıralamaAlgoritmaları.insertionSort(dizi1))); break;
    case "Bubble Sort" : sıralDizi.setText(Arrays.toString(SıralamaAlgoritmaları.bubbleSort(dizi1))); break;
}  
    }//GEN-LAST:event_AlgoritmalarActionPerformed

    private void DiziBoyutuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiziBoyutuActionPerformed
    
    }//GEN-LAST:event_DiziBoyutuActionPerformed

    private void CizdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CizdirActionPerformed
  if (DiziBoyutu.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Lütfen dizi boyutu girin!");
        return;
    }
   if (dizi1==null) {
        JOptionPane.showMessageDialog(this, "Lütfen Bir Algoritma Seçin!");
        return;
    }
   ArrayList<Integer> adimSayilari = new ArrayList();
adimSayilari.add(SıralamaAlgoritmalarıForSteps.selectionSort(dizi1)); 
adimSayilari.add(SıralamaAlgoritmalarıForSteps.insertionSort(dizi1)); 
adimSayilari.add(SıralamaAlgoritmalarıForSteps.bubbleSort(dizi1));


// Grafiği oluşturmak için gerekli veri setini oluşturuyoruz
JFrame frame = new JFrame();

// Grafiklerin gösterileceği panel oluşturuyoruz
JPanel panel = new JPanel(new GridLayout(0, 3)); // Bu panel tüm grafikleri yatay olarak sıralayacak

// Grafiği oluşturmak için gerekli veri setini oluşturuyoruz
DefaultCategoryDataset dataset1 = new DefaultCategoryDataset();
dataset1.addValue(adimSayilari.get(0), "Adım Sayısı", "Selection Sort");
JFreeChart chart1 = ChartFactory.createBarChart("Selection Sort Adım Sayısı", "Algoritma", "Adım Sayısı", dataset1, PlotOrientation.VERTICAL, false, true, false);
ChartPanel chartPanel1 = new ChartPanel(chart1);
panel.add(chartPanel1); // Grafiği panel'e ekliyoruz

DefaultCategoryDataset dataset2 = new DefaultCategoryDataset();
dataset2.addValue(adimSayilari.get(1), "Adım Sayısı", "Insertion Sort");
JFreeChart chart2 = ChartFactory.createBarChart("Insertion Sort Adım Sayısı", "Algoritma", "Adım Sayısı", dataset2, PlotOrientation.VERTICAL, false, true, false);
ChartPanel chartPanel2 = new ChartPanel(chart2);
panel.add(chartPanel2); // Grafiği panel'e ekliyoruz

DefaultCategoryDataset dataset3 = new DefaultCategoryDataset();
dataset3.addValue(adimSayilari.get(2), "Adım Sayısı", "Bubble Sort");
JFreeChart chart3 = ChartFactory.createBarChart("Bubble Sort Adım Sayısı", "Algoritma", "Adım Sayısı", dataset3, PlotOrientation.VERTICAL, false, true, false);
ChartPanel chartPanel3 = new ChartPanel(chart3);
panel.add(chartPanel3); // Grafiği panel'e ekliyoruz
panel.setPreferredSize(new java.awt.Dimension(700, 367));
// Paneli frame'e ekleyelim
frame.add(panel);
frame.pack();
frame.setVisible(true);
    }//GEN-LAST:event_CizdirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Algoritmalar;
    private javax.swing.JButton Cizdir;
    private javax.swing.JTextField DiziBoyutu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel sıralDizi;
    // End of variables declaration//GEN-END:variables
}
